#!/bin/bash

# Load environment variables from .env file
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Check if DB_URL is set
if [ -z "$DB_URL" ]; then
    echo "DB_URL is not set in the .env file."
    exit 1
fi

COMMAND=$1

cd ./sql/schema
goose postgres "$DB_URL" "$COMMAND"
cd ../..
